name: AWS Build and push image
on:
  workflow_dispatch:
    inputs:
      version_name:
        description: 'Version name'
        required: true
        default: 'latest'
jobs:
  push-container:
    runs-on: ubuntu-latest
    permissions: write-all
    defaults:
      run:
        working-directory: '.'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/looprock/rds_pg_anon:${{inputs.version_name}}
            ghcr.io/looprock/rds_pg_anon:dev-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./Dockerfile
